# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      patch:
        patterns:
          - '*'
        update-types:
          - 'patch'
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
        update-types:
          - 'minor'
          - 'patch'
      eslint:
        patterns:
          - '@encoura/eslint-config'
          - 'eslint-*'
      jest:
        patterns:
          - 'jest'
          - 'jest-*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      types:
        patterns:
          - '@types/*'